### ISSUE TITLE
avatar documentation confusing

### ISSUE THREAD

**Issue by krisbaum74** [ConnectyCube/connectycube-js-sdk-releases#20] opened 2020-04-29 00:08 UTC
https://developers.connectycube.com/js/authentication-and-users?id=user-avatar

upload an avatar as such ->

const updateUser = uploadedFile => {
    const updatedUserProfile = { avatar: uploadedFile.uid };
    // JS SDK v1
    // JS SDK v2
    ConnectyCube.users.update(updatedUserProfile);
};

which sets  avatar:

yet further down its stated use custom_Data.avatar_uid ?? 

const fileUID = JSON.parse(someUser.custom_data)['avatar_uid'];
const fileUrl = ConnectyCube.storage.privateUrl(fileUID);
const imageHTML = "<img src='" + fileUrl + "' alt='photo'/>";

**Comment by ccvlad** [comment] 2020-04-29 09:21
The idea is:
1. Upload some image via `ConnectyCube.storage.createAndUpload()`;
2. Get uploaded image's UID;
3. Add image's UID to the user's custom_data (string type, so you can add some JSON object);
4. Use `ConnectyCube.storage.privateUrl(UID)` to get image's URL.

**Comment by ccvlad** [comment] 2020-04-29 10:09
Also I have updated the confusing code in our docs.
Thank you for this note!

**Comment by ccvlad** [comment] 2020-05-08 09:52
I am going to close the issue, please re-open if the issue is still persists.

**Closed by ccvlad** 2020-05-08 09:52 UTC
