### ISSUE TITLE
Video Switch not working in iOS Cordova

### ISSUE THREAD

**Issue by Unixon-solutions** [ConnectyCube/connectycube-js-sdk-releases#39] opened 2020-07-23 13:00 UTC
Getting this error TypeError: undefined is not an object (evaluating 'e.track.kind') in key: "_replaceTracks",

```
const constraints = { video: deviceId };
videosession.switchMediaTracks(constraints)
       .then(stream => {})
        .catch(error => {}); 
```
This works in android and web (android and iOS both) but in iOS cordova its not working which uses cordova-plugin-iosrtc.
When above code get called video call get freezes.

**Comment by ccvlad** [comment] 2020-07-23 14:11
Hi, @Unixon-solutions 
Thanks for the report! We will check and fix or provide you a solution.

**Comment by Unixon-solutions** [comment] 2020-07-23 14:16
Thanks @ccvlad 
I have added this issue 17 days ago on `ConnectyCube/connectycube-cordova-samples ` but didn't get any reply yet.
https://github.com/ConnectyCube/connectycube-cordova-samples/issues/3#issue-651469702

**Comment by ccvlad** [comment] 2020-07-23 14:20
What the version of ConnectyCube SDK do you use?

**Comment by Unixon-solutions** [comment] 2020-07-23 14:24
I have used used old version and latest version 3.5.1 too

**Comment by ccvlad** [comment] 2020-07-23 14:29
Ok. I will update you in the **connectycube-cordova-samples** repo too

**Comment by Unixon-solutions** [comment] 2020-07-23 14:49
If its Js fix I will update JS 
If its code fix let me know so I can update it my code.

Thanks.

**Comment by ccvlad** [comment] 2020-07-30 21:36
Duplicate of ConnectyCube/connectycube-cordova-samples/issues/3

**Closed by ccvlad** 2020-07-30 21:36 UTC
